// SPDX-License-Identifier: MPL-2.0

/**
 * Issue #376 — `caelo-mcp-server export`: writes a CLAUDE.md + one
 * `.claude/skills/<slug>/SKILL.md` per active skill into a working
 * directory, generated from the install's live context
 * (`/api/mcp/context` with skill bodies included). Check the files into
 * the repo an external agent (Claude Code) works from so the site
 * context loads automatically at session start; re-run after skills or
 * site memory change.
 *
 * The renderers are pure and exported for tests; `runExport` does the
 * fetching + file I/O.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { postAdmin, resolveTimeoutMs } from "./http.js";

export interface ExportSkill {
  readonly slug: string;
  readonly displayName: string;
  readonly description: string;
  readonly allowlistedTools: string[];
  readonly body?: string;
}

export interface ExportContext {
  readonly systemContext: string;
  readonly statusLine: string | null;
  readonly skills: ReadonlyArray<ExportSkill>;
}

/** Path-safety gate for skill slugs — DB slugs already match this; a row
 *  that doesn't is skipped rather than allowed to escape the out dir. */
const SAFE_SLUG = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;

export function renderClaudeMd(context: ExportContext, generatedAt: string): string {
  const skillLines = context.skills.map((s) => `- ${s.slug}: ${s.description}`);
  return [
    "# Caelo site context",
    "",
    `<!-- Generated by \`caelo-mcp-server export\` at ${generatedAt}. Re-run to refresh; do not hand-edit. -->`,
    "",
    "This file describes the Caelo CMS install your `caelo-admin-mcp` MCP tools operate on.",
    "Work happens through those tools: call `caelo_open_session` once, make changes with the",
    "caelo tools (every write lands on the session's preview branch), and tell the operator to",
    "review + publish in the Caelo admin. Never claim a change is live.",
    "",
    context.systemContext,
    "",
    "## Site status",
    "",
    context.statusLine ?? "Base setup complete.",
    "",
    "## Skills",
    "",
    "Full skill instructions live in `.claude/skills/<slug>/SKILL.md` — read the matching file",
    "before the relevant work:",
    "",
    ...skillLines,
    "",
  ].join("\n");
}

export function renderSkillMd(skill: ExportSkill): string {
  return [
    "---",
    `name: ${skill.slug}`,
    `description: ${skill.description.replace(/\n/g, " ")}`,
    "---",
    "",
    skill.body ?? "",
    "",
  ].join("\n");
}

export interface RunExportOpts {
  readonly adminUrl: string;
  readonly token: string;
  /** Directory the CLAUDE.md + .claude/skills tree lands in. */
  readonly outDir: string;
}

/** Fetches the live context and writes the files. Returns written paths. */
export async function runExport(opts: RunExportOpts): Promise<string[]> {
  const context = await postAdmin<ExportContext>({
    adminUrl: opts.adminUrl,
    token: opts.token,
    path: "/api/mcp/context",
    body: { includeSkillBodies: true },
    timeoutMs: resolveTimeoutMs(60_000),
  });

  const written: string[] = [];
  const claudeMdPath = join(opts.outDir, "CLAUDE.md");
  await mkdir(opts.outDir, { recursive: true });
  await writeFile(claudeMdPath, renderClaudeMd(context, new Date().toISOString()), "utf8");
  written.push(claudeMdPath);

  for (const skill of context.skills) {
    if (!SAFE_SLUG.test(skill.slug)) {
      console.error(`skipping skill with unsafe slug: ${JSON.stringify(skill.slug)}`);
      continue;
    }
    const dir = join(opts.outDir, ".claude", "skills", skill.slug);
    await mkdir(dir, { recursive: true });
    const path = join(dir, "SKILL.md");
    await writeFile(path, renderSkillMd(skill), "utf8");
    written.push(path);
  }
  return written;
}
