// SPDX-License-Identifier: MPL-2.0

/**
 * The redirects table on Firebase Hosting: the generator's `_redirects`
 * file becomes `config.redirects`. Includes the shape a de (default) +
 * en site with `prefixDefaultLocale` produces — `/de` → `/` plus the
 * 301s of moving default-locale pages under `/de/`.
 */

import { describe, expect, it } from "bun:test";
import { firebaseRedirectsFromFile } from "../firebase-redirects.js";

const FILE = [
  "# Auto-generated by Caelo static-generator. Do not edit by hand.",
  "/de / 301",
  "/preise /de/preise 301",
  "/old.html /new.pdf 302",
  "/gone /410 410",
  "",
].join("\n");

describe("firebaseRedirectsFromFile", () => {
  it("matches each from-path with and without trailing slash and points at the directory URL", () => {
    expect(firebaseRedirectsFromFile(FILE, "directory")).toEqual([
      { regex: "^/de/?$", location: "/", statusCode: 301 },
      { regex: "^/preise/?$", location: "/de/preise/", statusCode: 301 },
      { regex: "^/old\\.html/?$", location: "/new.pdf", statusCode: 302 },
    ]);
  });

  it("keeps slash-less locations in the no-extension style", () => {
    const rules = firebaseRedirectsFromFile(FILE, "no-extension");
    expect(rules.map((r) => r.location)).toEqual(["/", "/de/preise", "/new.pdf"]);
  });

  it("matches the bare root exactly", () => {
    expect(firebaseRedirectsFromFile("/ /de 302\n", "directory")).toEqual([
      { regex: "^/$", location: "/de/", statusCode: 302 },
    ]);
  });

  it("escapes regex metacharacters in stored paths", () => {
    const [rule] = firebaseRedirectsFromFile("/a+b(c) /x 301\n", "directory");
    expect(rule?.regex).toBe("^/a\\+b\\(c\\)/?$");
    expect(new RegExp(rule?.regex ?? "").test("/a+b(c)/")).toBe(true);
    expect(new RegExp(rule?.regex ?? "").test("/aab(c)")).toBe(false);
  });

  it("fails loudly on a malformed line instead of dropping a redirect", () => {
    expect(() => firebaseRedirectsFromFile("/a b /c 301\n", "directory")).toThrow(/line 1/);
    expect(() => firebaseRedirectsFromFile("/a /b 200\n", "directory")).toThrow(/301, 302, 307/);
  });
});
