// SPDX-License-Identifier: MPL-2.0

/**
 * The redirects table on Firebase Hosting: the generator's `_redirects`
 * file becomes `config.redirects`. Includes the shape a de (default) +
 * en site with `prefixDefaultLocale` produces — `/de` → `/` plus the
 * 301s of moving default-locale pages under `/de/`.
 */

import { describe, expect, it } from "bun:test";
import { firebaseRedirectsFromFile } from "../firebase-redirects.js";

const FILE = [
  "# Auto-generated by Caelo static-generator. Do not edit by hand.",
  "/de / 301",
  "/preise /de/preise 301",
  "/old.html /new.pdf 302",
  "/gone /410 410",
  "",
].join("\n");

const NO_FILES: ReadonlySet<string> = new Set();

describe("firebaseRedirectsFromFile", () => {
  it("matches each from-path with and without trailing slash and points at the directory URL", () => {
    expect(firebaseRedirectsFromFile(FILE, "directory", NO_FILES)).toEqual([
      { regex: "^/de/?$", location: "/", statusCode: 301 },
      { regex: "^/preise/?$", location: "/de/preise/", statusCode: 301 },
      { regex: "^/old\\.html/?$", location: "/new.pdf", statusCode: 302 },
    ]);
  });

  it("keeps slash-less locations in the no-extension style", () => {
    const rules = firebaseRedirectsFromFile(FILE, "no-extension", NO_FILES);
    expect(rules.map((r) => r.location)).toEqual(["/", "/de/preise", "/new.pdf"]);
  });

  it("matches the bare root exactly", () => {
    expect(firebaseRedirectsFromFile("/ /de 302\n", "directory", NO_FILES)).toEqual([
      { regex: "^/$", location: "/de/", statusCode: 302 },
    ]);
  });

  it("escapes regex metacharacters in stored paths", () => {
    const [rule] = firebaseRedirectsFromFile("/a+b(c) /x 301\n", "directory", NO_FILES);
    expect(rule?.regex).toBe("^/a\\+b\\(c\\)/?$");
    expect(new RegExp(rule?.regex ?? "").test("/a+b(c)/")).toBe(true);
    expect(new RegExp(rule?.regex ?? "").test("/aab(c)")).toBe(false);
  });

  it("fails loudly on a malformed line instead of dropping a redirect", () => {
    expect(() => firebaseRedirectsFromFile("/a b /c 301\n", "directory", NO_FILES)).toThrow(
      /line 1/,
    );
    expect(() => firebaseRedirectsFromFile("/a /b 200\n", "directory", NO_FILES)).toThrow(
      /301, 302, 307/,
    );
  });

  // Hosting applies redirects BEFORE static content, so a recorded row
  // whose from-path is a live page again (here: the prefix opted out,
  // /preise back at /preise while /preise → /de/preise stays recorded
  // next to /de/preise → /preise) would shadow the page and loop.
  it("leaves out rules whose from-path a build file serves — the live page wins", () => {
    const file = "/preise /de/preise 301\n/de/preise /preise 301\n/de / 301\n/ /de 302\n";
    const directory = new Set(["index.html", "preise/index.html"]);
    expect(firebaseRedirectsFromFile(file, "directory", directory)).toEqual([
      { regex: "^/de/preise/?$", location: "/preise/", statusCode: 301 },
      { regex: "^/de/?$", location: "/", statusCode: 301 },
    ]);
    const noExtension = new Set(["index.html", "preise"]);
    expect(
      firebaseRedirectsFromFile(file, "no-extension", noExtension).map((r) => r.regex),
    ).toEqual(["^/de/preise/?$", "^/de/?$"]);
  });
});
