-- SPDX-License-Identifier: MPL-2.0
--
-- 0192 — meaningful media slugs. `media_assets.slug` is a human-facing,
-- URL-safe name (e.g. `searchviu-logo`) that becomes the public asset URL
-- (`/_assets/<slug>.<ext>`) and the admin preview URL (`/_caelo/media/<slug>`);
-- the UUID id stays internal. UNIQUE among live rows (collisions get a -N
-- suffix, generated by the upload op via resolveUniqueMediaSlug).
--
-- Backfill existing rows from `original_name` (best-effort slugify + de-dup)
-- so the column can be NOT NULL. Fresh installs have no rows → no-op backfill.

BEGIN;

SET LOCAL caelo.actor_kind = 'system';

ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS slug text;

-- Best-effort backfill: strip extension, lowercase, kebab-case, trim + cap,
-- then de-dup identical bases with a -N suffix (N = row rank). Covers ALL
-- rows (incl. soft-deleted) so the NOT NULL below holds.
WITH base AS (
  SELECT id,
         COALESCE(
           NULLIF(
             left(
               trim(both '-' from
                 regexp_replace(
                   lower(regexp_replace(original_name, '\.[a-z0-9]+$', '', 'i')),
                   '[^a-z0-9]+', '-', 'g'
                 )
               ),
               60
             ),
             ''
           ),
           'image'
         ) AS b
  FROM media_assets
  WHERE slug IS NULL
),
ranked AS (
  SELECT id, b, row_number() OVER (PARTITION BY b ORDER BY id) AS rn FROM base
)
UPDATE media_assets ma
   SET slug = CASE WHEN r.rn = 1 THEN r.b ELSE r.b || '-' || r.rn END
  FROM ranked r
 WHERE ma.id = r.id;

ALTER TABLE media_assets ALTER COLUMN slug SET NOT NULL;

-- Unique among LIVE rows only — soft-deleted rows may share a freed slug.
CREATE UNIQUE INDEX IF NOT EXISTS media_assets_slug_unique
  ON media_assets (slug) WHERE deleted_at IS NULL;

COMMIT;
