// SPDX-License-Identifier: MPL-2.0

/**
 * P14 — production docker-compose.yml generator.
 *
 * Emits the production stack: Postgres + pgBackRest sidecar + Caddy +
 * MinIO + four Caelo services (admin, gateway, orchestrator, runner).
 * Idempotent: same input → byte-identical output. The CLI's `up`
 * sub-command writes this to `<repo>/.caelo/docker-compose.yml` and
 * runs `docker compose up -d`.
 */

export interface ComposeSpec {
  readonly domain: string;
  readonly postgresPassword: string; // generated by cms-provision; persisted in .caelo/secrets
  readonly minioRootUser: string;
  readonly minioRootPassword: string;
  /**
   * P18 — project KEK (32 bytes hex) for at-rest encryption of AI provider
   * keys + future secrets. Generated per install by cms-provision; persisted
   * in `.caelo/secrets`. NEVER prompt the operator for this — auto-generated
   * via the same randomHex(32) the GCP stack uses.
   */
  readonly caeloSecretKek: string;
  readonly anthropicApiKey?: string;
  readonly resendApiKey?: string;
  readonly diskSize: string;
}

export function generateDockerCompose(spec: ComposeSpec): string {
  const env = (k: string, v: string | undefined): string =>
    v ? `      ${k}: "${escapeYaml(v)}"` : "";
  return `# SPDX-License-Identifier: MPL-2.0
# Generated by cms-provision — do not edit; re-run \`bunx cms-provision up\`.
# Domain: ${spec.domain}

services:
  postgres:
    image: postgres:16-alpine
    container_name: caelo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${escapeYaml(spec.postgresPassword)}"
      POSTGRES_USER: caelo
      POSTGRES_DB: caelo
    volumes:
      - caelo-pg:/var/lib/postgresql/data
      - ./bootstrap.sh:/docker-entrypoint-initdb.d/00_bootstrap.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caelo"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbackrest:
    image: pgbackrest/pgbackrest:latest
    container_name: caelo-pgbackrest
    restart: unless-stopped
    depends_on: [postgres]
    volumes:
      - caelo-pg-backups:/var/lib/pgbackrest
      - ./pgbackrest.conf:/etc/pgbackrest.conf:ro

  minio:
    image: minio/minio:latest
    container_name: caelo-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${escapeYaml(spec.minioRootUser)}"
      MINIO_ROOT_PASSWORD: "${escapeYaml(spec.minioRootPassword)}"
    volumes:
      - caelo-minio:/data

  caddy:
    image: caddy:2-alpine
    container_name: caelo-caddy
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caelo-caddy-data:/data
      - caelo-caddy-config:/config
      - ./output:/srv/caelo:ro

  caelo-admin:
    image: oven/bun:1.3
    container_name: caelo-admin
    restart: unless-stopped
    depends_on:
      postgres: { condition: service_healthy }
    working_dir: /app
    volumes:
      - ../..:/app
    command: bun run --filter @caelo-cms/admin start
    environment:
      ADMIN_DATABASE_URL: "postgres://caelo:${escapeYaml(spec.postgresPassword)}@postgres:5432/cms_admin"
      PUBLIC_ADMIN_DATABASE_URL: "postgres://caelo:${escapeYaml(spec.postgresPassword)}@postgres:5432/cms_public"
      CAELO_SECRET_KEK: "${escapeYaml(spec.caeloSecretKek)}"
      NODE_ENV: production
${env("ANTHROPIC_API_KEY", spec.anthropicApiKey)}
${env("RESEND_API_KEY", spec.resendApiKey)}

  caelo-gateway:
    image: oven/bun:1.3
    container_name: caelo-gateway
    restart: unless-stopped
    depends_on:
      postgres: { condition: service_healthy }
    working_dir: /app
    volumes:
      - ../..:/app
    command: bun run apps/api-gateway/src/server.ts
    environment:
      ADMIN_DATABASE_URL: "postgres://caelo:${escapeYaml(spec.postgresPassword)}@postgres:5432/cms_admin"
      PUBLIC_DATABASE_URL: "postgres://caelo:${escapeYaml(spec.postgresPassword)}@postgres:5432/cms_public"
      GATEWAY_PORT: "8090"
      NODE_ENV: production

volumes:
  caelo-pg:
  caelo-pg-backups:
  caelo-minio:
  caelo-caddy-data:
  caelo-caddy-config:
`;
}

function escapeYaml(s: string): string {
  // Conservative escape for double-quoted YAML strings.
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
