// SPDX-License-Identifier: MPL-2.0

/**
 * P14 — production docker-compose.yml generator.
 *
 * Emits the production stack: Postgres + pgBackRest sidecar + Caddy +
 * MinIO + four Caelo services (admin, gateway, orchestrator, runner).
 * Idempotent: same input → byte-identical output. The CLI's `up`
 * sub-command writes this to `<repo>/.caelo/docker-compose.yml` and
 * runs `docker compose up -d`.
 */

import { ADMIN_MEMORY_DEFAULT, memoryQuantityMiB, publicSiteUrl } from "./stack-contract.js";

/**
 * The application roles' passwords (bootstrap.sh creates the roles with
 * them). One per role, so the gateway — which gets only the public and
 * gateway logins — never holds admin_role's (#613, CLAUDE.md §2).
 */
export interface RolePasswords {
  readonly admin: string;
  readonly public: string;
  readonly gateway: string;
}

export interface ComposeSpec {
  readonly domain: string;
  /** The Postgres superuser's; only the database container uses it. */
  readonly postgresPassword: string; // generated by cms-provision; persisted in .caelo/secrets
  readonly rolePasswords: RolePasswords;
  readonly minioRootUser: string;
  readonly minioRootPassword: string;
  /**
   * P18 — project KEK (32 bytes hex) for at-rest encryption of AI provider
   * keys + future secrets. Generated per install by cms-provision; persisted
   * in `.caelo/secrets`. NEVER prompt the operator for this — auto-generated
   * via the same randomHex(32) the GCP stack uses.
   */
  readonly caeloSecretKek: string;
  readonly anthropicApiKey?: string;
  readonly resendApiKey?: string;
  readonly diskSize: string;
  /**
   * #553 — memory reserved for the admin (it runs the Lighthouse quality
   * audit). Same `adminMemory` knob + default as every adapter
   * (stack-contract.ts); compose reserves it rather than capping it, so a
   * busy host never OOM-kills the admin at the limit.
   */
  readonly adminMemory?: string;
}

export function generateDockerCompose(spec: ComposeSpec): string {
  const adminMemory = spec.adminMemory ?? ADMIN_MEMORY_DEFAULT;
  const adminMemoryMiB = memoryQuantityMiB(adminMemory);
  if (adminMemoryMiB === null) {
    throw new Error(`adminMemory "${adminMemory}" is not a memory quantity (e.g. 2Gi)`);
  }
  const env = (k: string, v: string | undefined): string =>
    v ? `      ${k}: "${escapeYaml(v)}"` : "";
  return `# SPDX-License-Identifier: MPL-2.0
# Generated by cms-provision — do not edit; re-run \`bunx cms-provision up\`.
# Domain: ${spec.domain}

services:
  postgres:
    image: postgres:16-alpine
    container_name: caelo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${escapeYaml(spec.postgresPassword)}"
      POSTGRES_USER: caelo
      POSTGRES_DB: caelo
      ADMIN_ROLE_PASSWORD: "${escapeYaml(spec.rolePasswords.admin)}"
      PUBLIC_ROLE_PASSWORD: "${escapeYaml(spec.rolePasswords.public)}"
      GATEWAY_ROLE_PASSWORD: "${escapeYaml(spec.rolePasswords.gateway)}"
    volumes:
      - caelo-pg:/var/lib/postgresql/data
      - ./bootstrap.sh:/docker-entrypoint-initdb.d/00_bootstrap.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caelo"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbackrest:
    image: pgbackrest/pgbackrest:latest
    container_name: caelo-pgbackrest
    restart: unless-stopped
    depends_on: [postgres]
    volumes:
      - caelo-pg-backups:/var/lib/pgbackrest
      - ./pgbackrest.conf:/etc/pgbackrest.conf:ro

  minio:
    image: minio/minio:latest
    container_name: caelo-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${escapeYaml(spec.minioRootUser)}"
      MINIO_ROOT_PASSWORD: "${escapeYaml(spec.minioRootPassword)}"
    volumes:
      - caelo-minio:/data

  caddy:
    image: caddy:2-alpine
    container_name: caelo-caddy
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caelo-caddy-data:/data
      - caelo-caddy-config:/config
      - ./output:/srv/caelo:ro

  caelo-admin:
    image: oven/bun:1.3
    container_name: caelo-admin
    restart: unless-stopped
    depends_on:
      postgres: { condition: service_healthy }
    working_dir: /app
    volumes:
      - ../..:/app
    command: bun run --filter @caelo-cms/admin start
    mem_reservation: ${adminMemoryMiB}m
    environment:
      ADMIN_DATABASE_URL: "${dbUrl("admin_role", spec.rolePasswords.admin, "cms_admin")}"
      PUBLIC_ADMIN_DATABASE_URL: "${dbUrl("admin_role", spec.rolePasswords.admin, "cms_public")}"
      CAELO_SECRET_KEK: "${escapeYaml(spec.caeloSecretKek)}"
      CAELO_SITE_URL: "${escapeYaml(publicSiteUrl(spec.domain))}"
      NODE_ENV: production
${env("ANTHROPIC_API_KEY", spec.anthropicApiKey)}
${env("RESEND_API_KEY", spec.resendApiKey)}

  caelo-gateway:
    image: oven/bun:1.3
    container_name: caelo-gateway
    restart: unless-stopped
    depends_on:
      postgres: { condition: service_healthy }
    working_dir: /app
    volumes:
      - ../..:/app
    command: bun run apps/api-gateway/src/server.ts
    environment:
      # Its own two logins only — no authoring credential (#613, CLAUDE.md §2).
      GATEWAY_DATABASE_URL: "${dbUrl("gateway_role", spec.rolePasswords.gateway, "cms_admin")}"
      PUBLIC_DATABASE_URL: "${dbUrl("public_role", spec.rolePasswords.public, "cms_public")}"
      GATEWAY_PORT: "8090"
      NODE_ENV: production

volumes:
  caelo-pg:
  caelo-pg-backups:
  caelo-minio:
  caelo-caddy-data:
  caelo-caddy-config:
`;
}

/** A compose-network database URL, password URL-encoded and YAML-escaped. */
function dbUrl(role: string, password: string, database: string): string {
  return escapeYaml(`postgres://${role}:${encodeURIComponent(password)}@postgres:5432/${database}`);
}

function escapeYaml(s: string): string {
  // Conservative escape for double-quoted YAML strings.
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
