// SPDX-License-Identifier: MPL-2.0

import { describe, expect, it } from "bun:test";
import { generateBootstrapToken } from "./bootstrap-token.js";
import { generateCaddyfile } from "./caddy.js";
import { loadCdnCopyAdapter, selfHostedCdnCopy } from "./cdn-copy.js";
import { generateDockerCompose } from "./compose.js";
import {
  emitRedirectsAzureFrontDoor,
  emitRedirectsCloudFront,
  emitRedirectsCloudflare,
  type RedirectRow,
} from "./redirects-emit.js";

describe("Caddyfile generator", () => {
  it("emits a vhost per domain + email block", () => {
    const out = generateCaddyfile({
      ownerEmail: "owner@example.com",
      publicSiteRoot: "/srv/caelo/output/production/current",
      stagingSiteRoot: "/srv/caelo/output/staging/current",
      adminPort: 5173,
      gatewayPort: 8090,
      domains: [
        { hostname: "example.com", kind: "public", env: "production" },
        { hostname: "staging.example.com", kind: "public", env: "staging" },
        { hostname: "admin.example.com", kind: "admin", env: "production" },
      ],
    });
    expect(out).toContain("email owner@example.com");
    expect(out).toContain("example.com {");
    expect(out).toContain("staging.example.com {");
    expect(out).toContain("admin.example.com {");
    // Staging gets noindex.
    const stagingBlock = out.match(/staging\.example\.com \{[^]*?\n\}/)?.[0] ?? "";
    expect(stagingBlock).toContain('X-Robots-Tag "noindex"');
    // Production does NOT get noindex.
    const productionBlock = out.match(/(?<!staging\.|admin\.)example\.com \{[^]*?\n\}/)?.[0] ?? "";
    expect(productionBlock).not.toContain('X-Robots-Tag "noindex"');
  });

  it("falls back to a localhost dev block when no domains configured", () => {
    const out = generateCaddyfile({
      ownerEmail: "x@y.z",
      publicSiteRoot: "/srv/caelo/output/production/current",
      stagingSiteRoot: "/srv/caelo/output/staging/current",
      adminPort: 5173,
      gatewayPort: 8090,
      domains: [],
    });
    expect(out).toContain(":8081 {");
    expect(out).toContain("reverse_proxy localhost:5173");
  });

  it("scopes locale-public vhosts to the per-locale dist subdir", () => {
    const out = generateCaddyfile({
      ownerEmail: "x@y.z",
      publicSiteRoot: "/srv/caelo/output/production/current",
      stagingSiteRoot: "/srv/caelo/output/staging/current",
      adminPort: 5173,
      gatewayPort: 8090,
      domains: [
        { hostname: "de.example.com", kind: "locale-public", localeCode: "de", env: "production" },
      ],
    });
    expect(out).toContain("root * /srv/caelo/output/production/current/de");
  });
});

describe("docker-compose generator", () => {
  it("emits postgres + caddy + caelo services with the supplied secrets", () => {
    const out = generateDockerCompose({
      domain: "example.com",
      postgresPassword: "supersecret",
      minioRootUser: "caelo",
      minioRootPassword: "miniopass",
      anthropicApiKey: "sk-ant-…",
      diskSize: "20Gi",
    });
    expect(out).toContain("caelo-postgres");
    expect(out).toContain("caelo-caddy");
    expect(out).toContain("caelo-admin");
    expect(out).toContain("caelo-gateway");
    expect(out).toContain("supersecret");
    expect(out).toContain("miniopass");
    expect(out).toContain("ANTHROPIC_API_KEY");
  });

  it("escapes secrets containing quotes safely", () => {
    const out = generateDockerCompose({
      domain: "example.com",
      postgresPassword: 'pa"ss',
      minioRootUser: "caelo",
      minioRootPassword: "x",
      diskSize: "1Gi",
    });
    expect(out).toContain('pa\\"ss');
  });
});

describe("bootstrap token generator", () => {
  it("emits 64 hex chars + ~24h expiry", () => {
    const t = generateBootstrapToken();
    expect(t.token).toMatch(/^[0-9a-f]{64}$/);
    const ttlHours = (Date.parse(t.expiresAt) - Date.now()) / 3600_000;
    expect(ttlHours).toBeGreaterThan(23);
    expect(ttlHours).toBeLessThan(25);
  });

  it("each call returns a unique token", () => {
    const a = generateBootstrapToken().token;
    const b = generateBootstrapToken().token;
    expect(a).not.toBe(b);
  });
});

describe("redirects-emit", () => {
  const rows: RedirectRow[] = [
    { fromPath: "/old", toPath: "/new", statusCode: 301 },
    { fromPath: "/blog/2024", toPath: "/blog", statusCode: 302 },
    { fromPath: "/legacy", toPath: "/modern", statusCode: 308 },
  ];

  describe("emitRedirectsCloudflare", () => {
    it("emits one line per row in `<from> <to> <status>` format", () => {
      const out = emitRedirectsCloudflare(rows);
      expect(out).toContain("/old /new 301\n");
      expect(out).toContain("/blog/2024 /blog 302\n");
      expect(out).toContain("/legacy /modern 308\n");
      expect(out.startsWith("# Generated by @caelo-cms/provisioning")).toBe(true);
    });

    it("empty rows → header only, no trailing newline noise", () => {
      const out = emitRedirectsCloudflare([]);
      expect(out).toBe("# Generated by @caelo-cms/provisioning — do not edit by hand.\n");
    });

    it("is byte-identical for the same input (deterministic)", () => {
      expect(emitRedirectsCloudflare(rows)).toBe(emitRedirectsCloudflare([...rows]));
    });
  });

  describe("emitRedirectsCloudFront", () => {
    it("returns parseable JSON config + a Lambda source that consumes it", () => {
      const out = emitRedirectsCloudFront(rows);
      const parsed = JSON.parse(out.jsonConfig) as {
        redirects: Array<{ from: string; to: string; status: number }>;
      };
      expect(parsed.redirects).toHaveLength(3);
      expect(parsed.redirects[0]).toEqual({ from: "/old", to: "/new", status: 301 });
      expect(out.lambdaSource).toContain("exports.handler");
      expect(out.lambdaSource).toContain('require("./redirects.json")');
    });

    it("preserves status codes verbatim (301/302/307/308)", () => {
      const allStatuses: RedirectRow[] = [
        { fromPath: "/a", toPath: "/x", statusCode: 301 },
        { fromPath: "/b", toPath: "/x", statusCode: 302 },
        { fromPath: "/c", toPath: "/x", statusCode: 307 },
        { fromPath: "/d", toPath: "/x", statusCode: 308 },
      ];
      const out = emitRedirectsCloudFront(allStatuses);
      const parsed = JSON.parse(out.jsonConfig) as {
        redirects: Array<{ status: number }>;
      };
      expect(parsed.redirects.map((r) => r.status)).toEqual([301, 302, 307, 308]);
    });
  });

  describe("emitRedirectsAzureFrontDoor", () => {
    it("emits one rule per row with monotonically-increasing order", () => {
      const out = emitRedirectsAzureFrontDoor(rows);
      expect(out).toHaveLength(3);
      expect(out[0]?.name).toBe("redirect-1");
      expect(out[0]?.order).toBe(1);
      expect(out[2]?.order).toBe(3);
    });

    it("maps status codes to Front Door redirectType vocabulary", () => {
      const out = emitRedirectsAzureFrontDoor([
        { fromPath: "/a", toPath: "/x", statusCode: 301 },
        { fromPath: "/b", toPath: "/x", statusCode: 302 },
        { fromPath: "/c", toPath: "/x", statusCode: 307 },
        { fromPath: "/d", toPath: "/x", statusCode: 308 },
      ]);
      expect(out.map((r) => r.actions[0]?.parameters.redirectType)).toEqual([
        "Moved",
        "Found",
        "TemporaryRedirect",
        "PermanentRedirect",
      ]);
    });

    it("RequestUri condition matches the from path exactly", () => {
      const out = emitRedirectsAzureFrontDoor(rows);
      expect(out[1]?.conditions[0]?.parameters.matchValues).toEqual(["/blog/2024"]);
      expect(out[1]?.actions[0]?.parameters.destinationPath).toBe("/blog");
    });
  });

  describe("path-validation guard (review-pass #9)", () => {
    it("Cloudflare emitter rejects fromPath with whitespace", () => {
      expect(() =>
        emitRedirectsCloudflare([{ fromPath: "/old path", toPath: "/new", statusCode: 301 }]),
      ).toThrow(/contains whitespace/);
    });

    it("CloudFront emitter rejects toPath with newline", () => {
      expect(() =>
        emitRedirectsCloudFront([{ fromPath: "/old", toPath: "/new\nlies", statusCode: 301 }]),
      ).toThrow(/contains whitespace/);
    });

    it("Azure emitter rejects tab in path", () => {
      expect(() =>
        emitRedirectsAzureFrontDoor([{ fromPath: "/old\there", toPath: "/x", statusCode: 301 }]),
      ).toThrow(/contains whitespace/);
    });

    it("hyphens, dots, slashes, unicode in path segments are accepted", () => {
      // Regression guard for the original buggy regex `[\s -]` which
      // rejected hyphens.
      expect(() =>
        emitRedirectsCloudflare([
          { fromPath: "/blog/spring-launch", toPath: "/blog/sommer-2026", statusCode: 301 },
        ]),
      ).not.toThrow();
    });
  });
});

describe("cdn-copy adapter loader", () => {
  it("returns the no-op self-hosted adapter when provider is unset/empty/self-hosted", async () => {
    expect(await loadCdnCopyAdapter(undefined)).toBe(selfHostedCdnCopy);
    expect(await loadCdnCopyAdapter("")).toBe(selfHostedCdnCopy);
    expect(await loadCdnCopyAdapter("self-hosted")).toBe(selfHostedCdnCopy);
  });

  it("self-hosted adapter pin returns a /media/<key> URL", async () => {
    const url = await selfHostedCdnCopy.pin("photos/2026/april/sunset.webp");
    expect(url).toBe("/media/photos/2026/april/sunset.webp");
  });

  it("rejects unknown provider names loudly (no silent fallback per CLAUDE.md §2)", async () => {
    await expect(loadCdnCopyAdapter("digitalocean")).rejects.toThrow(/unknown CAELO_PROVIDER/);
  });
});
