// SPDX-License-Identifier: MPL-2.0

/**
 * P15 — per-provider redirect file generators.
 *
 * P14's self-hosted Caddy consumes a `_redirects.caddy` file. Cloud
 * providers want different formats: Cloudflare Pages reads `_redirects`
 * (also a fine fit for any platform that consumes that format),
 * CloudFront wants a JSON config a Lambda@Edge function reads at
 * startup, and Azure Front Door wants a rules-engine RuleEngineRule[].
 *
 * The deploy step calls the right emitter based on `process.env.CAELO_PROVIDER`
 * and uploads the result to the right place. Each emitter is pure +
 * idempotent — same input → same byte output.
 */

export type RedirectStatusCode = 301 | 302 | 307 | 308;

export interface RedirectRow {
  readonly fromPath: string;
  readonly toPath: string;
  readonly statusCode: RedirectStatusCode;
}

/**
 * Reject whitespace + control chars in either path before any emitter
 * touches them. The Cloudflare `_redirects` format is space-delimited;
 * a `fromPath` containing a space ambiguates the line (CF parses
 * `/old foo /new 301` as from=`/old`, to=`foo`, status=`/new`, then
 * fails on `301`). Caelo's redirects table normally rejects these
 * upstream but the emitter shouldn't trust that — pure functions
 * defend their own contract.
 */
function assertPathClean(label: "fromPath" | "toPath", path: string): void {
  if (/[\s\x00-\x1f]/.test(path)) {
    throw new Error(
      `redirects-emit: ${label}=${JSON.stringify(path)} contains whitespace or control chars; reject upstream`,
    );
  }
}

function assertRowsClean(rows: ReadonlyArray<RedirectRow>): void {
  for (const r of rows) {
    assertPathClean("fromPath", r.fromPath);
    assertPathClean("toPath", r.toPath);
  }
}

/**
 * Cloudflare Pages `_redirects` format (also consumed by Netlify, Vercel,
 * Render, etc.). One redirect per line: `<from> <to> <status>`. Wildcards
 * use `:splat`; we only support exact-path redirects in v1 (matches what
 * Caelo's redirects table allows).
 */
export function emitRedirectsCloudflare(rows: ReadonlyArray<RedirectRow>): string {
  assertRowsClean(rows);
  const header = "# Generated by @caelo-cms/provisioning — do not edit by hand.\n";
  const lines = rows.map((r) => `${r.fromPath} ${r.toPath} ${r.statusCode}`);
  return header + lines.join("\n") + (rows.length > 0 ? "\n" : "");
}

/**
 * CloudFront via Lambda@Edge. Returns a JSON config the L@E function
 * reads at startup + a tiny Lambda source that consumes it. The L@E
 * function is deployed to `us-east-1` (CloudFront constraint); the
 * config blob is bundled into the Lambda deployment artifact.
 *
 * Returning both halves lets the AWS stack ship a single asset.
 */
export interface CloudFrontRedirectArtifact {
  readonly jsonConfig: string;
  readonly lambdaSource: string;
}

export function emitRedirectsCloudFront(
  rows: ReadonlyArray<RedirectRow>,
): CloudFrontRedirectArtifact {
  assertRowsClean(rows);
  const jsonConfig = JSON.stringify(
    { redirects: rows.map((r) => ({ from: r.fromPath, to: r.toPath, status: r.statusCode })) },
    null,
    2,
  );
  // Tiny Lambda@Edge handler. v1 is exact-path match (matches Caelo's
  // redirects table). Wildcard support lands when the table grows it.
  const lambdaSource = `// SPDX-License-Identifier: MPL-2.0
// Generated by @caelo-cms/provisioning. Bundled with redirects.json.
const REDIRECTS = require("./redirects.json").redirects;
const TABLE = new Map(REDIRECTS.map((r) => [r.from, r]));
exports.handler = (event, _ctx, callback) => {
  const req = event.Records[0].cf.request;
  const m = TABLE.get(req.uri);
  if (!m) return callback(null, req);
  callback(null, {
    status: String(m.status),
    statusDescription: "Redirect",
    headers: { location: [{ key: "Location", value: m.to }] },
  });
};`;
  return { jsonConfig, lambdaSource };
}

/**
 * Azure Front Door rules engine. Returns a Pulumi-compatible
 * RuleEngineRule[]-shaped array (untyped here so callers don't need to
 * import @pulumi/azure-native). Each rule fires on a path-equals match
 * + executes a 301/302/etc. response.
 */
export interface FrontDoorRule {
  readonly name: string;
  readonly order: number;
  readonly conditions: ReadonlyArray<{
    readonly name: "RequestUri";
    readonly parameters: {
      readonly operator: "Equal";
      readonly matchValues: ReadonlyArray<string>;
    };
  }>;
  readonly actions: ReadonlyArray<{
    readonly name: "UrlRedirect";
    readonly parameters: {
      readonly redirectType: "Moved" | "Found" | "TemporaryRedirect" | "PermanentRedirect";
      readonly destinationPath: string;
    };
  }>;
}

export function emitRedirectsAzureFrontDoor(
  rows: ReadonlyArray<RedirectRow>,
): ReadonlyArray<FrontDoorRule> {
  assertRowsClean(rows);
  return rows.map((r, i) => ({
    name: `redirect-${i + 1}`,
    order: i + 1,
    conditions: [
      {
        name: "RequestUri" as const,
        parameters: { operator: "Equal" as const, matchValues: [r.fromPath] },
      },
    ],
    actions: [
      {
        name: "UrlRedirect" as const,
        parameters: {
          redirectType: statusToFrontDoor(r.statusCode),
          destinationPath: r.toPath,
        },
      },
    ],
  }));
}

function statusToFrontDoor(
  status: RedirectStatusCode,
): FrontDoorRule["actions"][0]["parameters"]["redirectType"] {
  switch (status) {
    case 301:
      return "Moved";
    case 302:
      return "Found";
    case 307:
      return "TemporaryRedirect";
    case 308:
      return "PermanentRedirect";
  }
}
