// SPDX-License-Identifier: MPL-2.0

/**
 * Where each cloud service the provider adapters need is offered — the data
 * behind the region catalogs in regions.ts (#607). Every list cites the
 * provider documentation it was copied from; update it from there (and
 * re-run regions.test.ts) when a provider adds regions.
 */

/** One installable region. */
export interface RegionOption {
  readonly id: string;
  /** Human-readable location, for the picker. */
  readonly name: string;
}

// ===========================================================================
// GCP — per-service region lists (checked 2026-10)
// ===========================================================================

export const GCP_REGION_NAMES: Readonly<Record<string, string>> = {
  "africa-south1": "Johannesburg",
  "asia-east1": "Taiwan",
  "asia-east2": "Hong Kong",
  "asia-northeast1": "Tokyo",
  "asia-northeast2": "Osaka",
  "asia-northeast3": "Seoul",
  "asia-south1": "Mumbai",
  "asia-south2": "Delhi",
  "asia-southeast1": "Singapore",
  "asia-southeast2": "Jakarta",
  "asia-southeast3": "Bangkok",
  "australia-southeast1": "Sydney",
  "australia-southeast2": "Melbourne",
  "europe-central2": "Warsaw",
  "europe-north1": "Finland",
  "europe-north2": "Stockholm",
  "europe-southwest1": "Madrid",
  "europe-west1": "Belgium",
  "europe-west2": "London",
  "europe-west3": "Frankfurt",
  "europe-west4": "Netherlands",
  "europe-west6": "Zurich",
  "europe-west8": "Milan",
  "europe-west9": "Paris",
  "europe-west10": "Berlin",
  "europe-west12": "Turin",
  "me-central1": "Doha",
  "me-central2": "Dammam",
  "me-west1": "Tel Aviv",
  "northamerica-northeast1": "Montréal",
  "northamerica-northeast2": "Toronto",
  "northamerica-south1": "Mexico",
  "southamerica-east1": "São Paulo",
  "southamerica-west1": "Santiago",
  "us-central1": "Iowa",
  "us-east1": "South Carolina",
  "us-east4": "Northern Virginia",
  "us-east5": "Columbus",
  "us-south1": "Dallas",
  "us-west1": "Oregon",
  "us-west2": "Los Angeles",
  "us-west3": "Salt Lake City",
  "us-west4": "Las Vegas",
};

/**
 * Where each regional GCP service the stacks and the CLI use is offered.
 * Global services (load balancer, Cloud CDN, Cloud Armor, IAP, Firebase
 * Hosting) don't constrain the region and are not listed.
 */
export const GCP_SERVICE_REGIONS: Readonly<Record<string, readonly string[]>> = {
  // https://docs.cloud.google.com/run/docs/locations
  "Cloud Run": [
    "asia-east1",
    "asia-northeast1",
    "asia-northeast2",
    "asia-south1",
    "asia-southeast3",
    "europe-north1",
    "europe-north2",
    "europe-southwest1",
    "europe-west1",
    "europe-west4",
    "europe-west8",
    "europe-west9",
    "me-west1",
    "northamerica-south1",
    "us-central1",
    "us-east1",
    "us-east4",
    "us-east5",
    "us-south1",
    "us-west1",
    "africa-south1",
    "asia-east2",
    "asia-northeast3",
    "asia-southeast1",
    "asia-southeast2",
    "asia-south2",
    "australia-southeast1",
    "australia-southeast2",
    "europe-central2",
    "europe-west10",
    "europe-west12",
    "europe-west2",
    "europe-west3",
    "europe-west6",
    "me-central1",
    "me-central2",
    "northamerica-northeast1",
    "northamerica-northeast2",
    "southamerica-east1",
    "southamerica-west1",
    "us-west2",
    "us-west3",
    "us-west4",
  ],
  // https://docs.cloud.google.com/sql/docs/postgres/locations
  "Cloud SQL": [
    "africa-south1",
    "asia-east1",
    "asia-east2",
    "asia-northeast1",
    "asia-northeast2",
    "asia-northeast3",
    "asia-south1",
    "asia-south2",
    "asia-southeast1",
    "asia-southeast2",
    "australia-southeast1",
    "australia-southeast2",
    "europe-central2",
    "europe-north1",
    "europe-southwest1",
    "europe-west1",
    "europe-west2",
    "europe-west3",
    "europe-west4",
    "europe-west6",
    "europe-west8",
    "europe-west9",
    "europe-west10",
    "europe-west12",
    "me-central1",
    "me-central2",
    "me-west1",
    "northamerica-northeast1",
    "northamerica-northeast2",
    "northamerica-south1",
    "us-central1",
    "us-south1",
    "us-east1",
    "us-east4",
    "us-east5",
    "us-west1",
    "us-west2",
    "us-west3",
    "us-west4",
    "southamerica-east1",
    "southamerica-west1",
  ],
  // https://docs.cloud.google.com/secret-manager/docs/locations — the stacks
  // replicate secrets user-managed into the install region.
  "Secret Manager": [
    "asia-south2",
    "asia-east2",
    "asia-southeast2",
    "australia-southeast2",
    "asia-south1",
    "asia-northeast2",
    "asia-northeast3",
    "asia-southeast1",
    "australia-southeast1",
    "asia-east1",
    "asia-northeast1",
    "asia-southeast3",
    "europe-west1",
    "europe-west10",
    "europe-north1",
    "europe-north2",
    "europe-west3",
    "europe-west2",
    "europe-southwest1",
    "europe-west8",
    "europe-west4",
    "europe-west12",
    "europe-west9",
    "europe-central2",
    "europe-west6",
    "us-central1",
    "us-west4",
    "us-west2",
    "northamerica-south1",
    "northamerica-northeast1",
    "us-east4",
    "us-west1",
    "us-west3",
    "us-east1",
    "northamerica-northeast2",
    "us-east5",
    "us-south1",
    "southamerica-east1",
    "southamerica-west1",
    "me-central2",
    "me-central1",
    "me-west1",
    "africa-south1",
  ],
  // https://docs.cloud.google.com/artifact-registry/docs/repositories/repo-locations
  "Artifact Registry": [
    "northamerica-northeast1",
    "northamerica-northeast2",
    "northamerica-south1",
    "us-central1",
    "us-east1",
    "us-east4",
    "us-east5",
    "us-south1",
    "us-west1",
    "us-west2",
    "us-west3",
    "us-west4",
    "southamerica-east1",
    "southamerica-west1",
    "europe-central2",
    "europe-north1",
    "europe-north2",
    "europe-southwest1",
    "europe-west1",
    "europe-west2",
    "europe-west3",
    "europe-west4",
    "europe-west6",
    "europe-west8",
    "europe-west9",
    "europe-west10",
    "europe-west12",
    "me-central1",
    "me-central2",
    "me-west1",
    "asia-east1",
    "asia-east2",
    "asia-northeast1",
    "asia-northeast2",
    "asia-northeast3",
    "asia-south1",
    "asia-south2",
    "asia-southeast1",
    "asia-southeast2",
    "asia-southeast3",
    "australia-southeast1",
    "australia-southeast2",
    "africa-south1",
  ],
  // https://docs.cloud.google.com/scheduler/docs/locations — the hourly
  // operator-access sync (operator-access.ts) schedules in the install region.
  "Cloud Scheduler": [
    "northamerica-northeast1",
    "northamerica-northeast2",
    "southamerica-east1",
    "us-central1",
    "us-east1",
    "us-east4",
    "us-south1",
    "us-west1",
    "us-west2",
    "us-west3",
    "us-west4",
    "europe-central2",
    "europe-west1",
    "europe-west2",
    "europe-west3",
    "europe-west4",
    "europe-west6",
    "europe-west8",
    "europe-west9",
    "europe-west12",
    "asia-east1",
    "asia-east2",
    "asia-northeast1",
    "asia-northeast2",
    "asia-northeast3",
    "asia-south1",
    "asia-south2",
    "asia-southeast1",
    "asia-southeast2",
    "asia-southeast3",
    "australia-southeast1",
    "me-central1",
    "me-central2",
    "me-west1",
  ],
  // https://docs.cloud.google.com/run/docs/mapping-custom-domains#limitations —
  // gcp-firebase serves admin.<domain> through a Cloud Run domain mapping.
  "Cloud Run domain mapping": [
    "asia-east1",
    "asia-northeast1",
    "asia-southeast1",
    "europe-north1",
    "europe-west1",
    "europe-west4",
    "us-central1",
    "us-east1",
    "us-east4",
    "us-west1",
  ],
};

/**
 * Regions Google offers only under special terms, so they are never offered
 * as a general install target even though the services exist there:
 * me-central2 (Dammam) is for KSA customers through Google's designated
 * reseller (https://docs.cloud.google.com/docs/dammam-region-access).
 */
export const GCP_RESTRICTED_REGIONS: readonly string[] = ["me-central2"];

export const GCP_SERVICES = [
  "Cloud Run",
  "Cloud SQL",
  "Secret Manager",
  "Artifact Registry",
  "Cloud Scheduler",
] as const;

// ===========================================================================
// AWS — https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate-Regions.html
// Fargate is the narrowest service the stack uses; RDS for PostgreSQL, S3,
// Secrets Manager and ACM are offered in every commercial region
// (https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/).
// GovCloud and China partitions are out of scope.
// ===========================================================================

export const AWS_REGIONS: readonly RegionOption[] = [
  { id: "us-east-1", name: "N. Virginia" },
  { id: "us-east-2", name: "Ohio" },
  { id: "us-west-1", name: "N. California" },
  { id: "us-west-2", name: "Oregon" },
  { id: "ca-central-1", name: "Canada Central" },
  { id: "ca-west-1", name: "Calgary" },
  { id: "mx-central-1", name: "Mexico Central" },
  { id: "sa-east-1", name: "São Paulo" },
  { id: "eu-central-1", name: "Frankfurt" },
  { id: "eu-central-2", name: "Zurich" },
  { id: "eu-west-1", name: "Ireland" },
  { id: "eu-west-2", name: "London" },
  { id: "eu-west-3", name: "Paris" },
  { id: "eu-south-1", name: "Milan" },
  { id: "eu-south-2", name: "Spain" },
  { id: "eu-north-1", name: "Stockholm" },
  { id: "af-south-1", name: "Cape Town" },
  { id: "il-central-1", name: "Tel Aviv" },
  { id: "me-south-1", name: "Bahrain" },
  { id: "me-central-1", name: "UAE" },
  { id: "ap-east-1", name: "Hong Kong" },
  { id: "ap-south-1", name: "Mumbai" },
  { id: "ap-south-2", name: "Hyderabad" },
  { id: "ap-northeast-1", name: "Tokyo" },
  { id: "ap-northeast-2", name: "Seoul" },
  { id: "ap-northeast-3", name: "Osaka" },
  { id: "ap-southeast-1", name: "Singapore" },
  { id: "ap-southeast-2", name: "Sydney" },
  { id: "ap-southeast-3", name: "Jakarta" },
  { id: "ap-southeast-4", name: "Melbourne" },
  { id: "ap-southeast-5", name: "Malaysia" },
  { id: "ap-southeast-7", name: "Thailand" },
];

// ===========================================================================
// Azure — Azure Database for PostgreSQL flexible server regions
// (https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview,
// "Azure regions"), minus access-restricted, Government and China regions.
// Container Apps has no static list; Microsoft names `az provider show` as the
// source (https://learn.microsoft.com/en-us/azure/container-apps/faq), so the
// catalog checks it live (see `queryAzureContainerAppsRegions`).
// ===========================================================================

export const AZURE_REGIONS: readonly RegionOption[] = [
  { id: "westeurope", name: "West Europe (Netherlands)" },
  { id: "northeurope", name: "North Europe (Ireland)" },
  { id: "germanywestcentral", name: "Germany West Central" },
  { id: "francecentral", name: "France Central" },
  { id: "francesouth", name: "France South" },
  { id: "swedencentral", name: "Sweden Central" },
  { id: "switzerlandnorth", name: "Switzerland North" },
  { id: "norwaywest", name: "Norway West" },
  { id: "austriaeast", name: "Austria East" },
  { id: "belgiumcentral", name: "Belgium Central" },
  { id: "italynorth", name: "Italy North" },
  { id: "polandcentral", name: "Poland Central" },
  { id: "spaincentral", name: "Spain Central" },
  { id: "uksouth", name: "UK South" },
  { id: "ukwest", name: "UK West" },
  { id: "eastus", name: "East US" },
  { id: "eastus2", name: "East US 2" },
  { id: "centralus", name: "Central US" },
  { id: "northcentralus", name: "North Central US" },
  { id: "southcentralus", name: "South Central US" },
  { id: "westcentralus", name: "West Central US" },
  { id: "westus", name: "West US" },
  { id: "westus2", name: "West US 2" },
  { id: "westus3", name: "West US 3" },
  { id: "canadacentral", name: "Canada Central" },
  { id: "canadaeast", name: "Canada East" },
  { id: "mexicocentral", name: "Mexico Central" },
  { id: "brazilsouth", name: "Brazil South" },
  { id: "chilecentral", name: "Chile Central" },
  { id: "southafricanorth", name: "South Africa North" },
  { id: "israelcentral", name: "Israel Central" },
  { id: "qatarcentral", name: "Qatar Central" },
  { id: "uaenorth", name: "UAE North" },
  { id: "centralindia", name: "Central India" },
  { id: "southindia", name: "South India" },
  { id: "jioindiacentral", name: "Jio India Central" },
  { id: "jioindiawest", name: "Jio India West" },
  { id: "eastasia", name: "East Asia (Hong Kong)" },
  { id: "southeastasia", name: "Southeast Asia (Singapore)" },
  { id: "japaneast", name: "Japan East" },
  { id: "japanwest", name: "Japan West" },
  { id: "koreacentral", name: "Korea Central" },
  { id: "koreasouth", name: "Korea South" },
  { id: "indonesiacentral", name: "Indonesia Central" },
  { id: "malaysiawest", name: "Malaysia West" },
  { id: "australiaeast", name: "Australia East" },
  { id: "australiasoutheast", name: "Australia Southeast" },
  { id: "australiacentral", name: "Australia Central" },
  { id: "newzealandnorth", name: "New Zealand North" },
];
